run_name: fusion_wo_ease_validated
model: fusion
ks:
- 10
- 20
batch_size: 2048
sample_topk_users: 20
fusion:
  normalize: zscore
  components:
  - name: itemknn
    normalize: cosine
    topk: 100
    shrink: 100.0
    weight: -0.01863227471269585
  - name: rp3beta
    alpha: 0.9
    beta: 0.2
    topk: 300
    weight: 0.5938109598468735
  - name: popularity
    weight: -0.14508103278837758
  - name: kg_profile
    weight: 0.09172402000616936
kg:
  use_concept: true
  use_field: true
  use_parent: true
  use_teacher: true
  use_school: true
  use_prerequisite: true
  max_df_ratio: 0.35
  min_df: 2
  top_features_per_course: 500
